sh_binary(
  name = "pip_pkg",
  srcs = ["pip_pkg.sh"],
  data = [
    "README.md",
    "required_packages.py",
    "setup.py",
    "//tensorflow_probability",
    "//tensorflow_probability/substrates",
  ],
)
